[platformio]
default_envs = H1, H2, B1, B2

[env]
platform = espressif32@6.9.0
board = esp32-c3-devkitm-1
framework = arduino
platform_packages = platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
lib_deps = bblanchon/ArduinoJson@6.21.5
monitor_speed = 115200
board_build.flash_mode = dio
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0

[env:H1]
build_flags = ${env.build_flags} -D ROBOT_ID=\"H1\" -D ROBOT_SERVO_COUNT=1 -D HAS_DISC_SENSOR=1

[env:H2]
build_flags = ${env.build_flags} -D ROBOT_ID=\"H2\" -D ROBOT_SERVO_COUNT=2 -D HAS_DISC_SENSOR=0

[env:B1]
build_flags = ${env.build_flags} -D ROBOT_ID=\"B1\" -D ROBOT_SERVO_COUNT=2 -D HAS_DISC_SENSOR=0

[env:B2]
build_flags = ${env.build_flags} -D ROBOT_ID=\"B2\" -D ROBOT_SERVO_COUNT=2 -D HAS_DISC_SENSOR=0
